name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.5.4
      - run: deno run --allow-run --allow-read https://deno.land/x/denopack@0.10.0/install.ts
      - run: denopack -c denopack.config.ts
      - run: |
          echo "/*    /index.html   200" >> dist/_redirects

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dist'
          comment-on-commit: true